# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.portMessagesTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.portMessagesTextEdit.setMaximumSize(QtCore.QSize(16777215, 200))
        self.portMessagesTextEdit.setReadOnly(True)
        self.portMessagesTextEdit.setObjectName("portMessagesTextEdit")
        self.verticalLayout_2.addWidget(self.portMessagesTextEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.portListComboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.portListComboBox.setObjectName("portListComboBox")
        self.horizontalLayout_2.addWidget(self.portListComboBox)
        self.refreshPortsPushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.refreshPortsPushButton.setObjectName("refreshPortsPushButton")
        self.horizontalLayout_2.addWidget(self.refreshPortsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.startRecordPushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.startRecordPushButton.setObjectName("startRecordPushButton")
        self.verticalLayout.addWidget(self.startRecordPushButton)
        self.resetButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout.addWidget(self.resetButton)
        self.isRecordingLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.isRecordingLabel.setObjectName("isRecordingLabel")
        self.verticalLayout.addWidget(self.isRecordingLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Прослушечка"))
        self.label.setText(_translate("MainWindow", "Порт"))
        self.refreshPortsPushButton.setText(_translate("MainWindow", "Обновить"))
        self.startRecordPushButton.setText(_translate("MainWindow", "Начать запись"))
        self.resetButton.setText(_translate("MainWindow", "Очистить"))
        self.isRecordingLabel.setText(_translate("MainWindow", "Слушаем..."))
